version: "3"
services:
  spring-boot-oauth2-auth-server:
    container_name: spring-boot-oauth2-auth-server
    image: "registry.gitlab.com/bittokazi/spring-boot-oauth2-multi-tenant-auth-server/backend:latest"
    restart: unless-stopped
    env_file: ./prod.env
    volumes:
      - /home/debian/data/certs:/certs
    network_mode: "bridge"
    ports:
      - "45020:5020"
