name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Trigger
        uses: fjogeleit/http-request-action@v1.14.2
        with:
          url: https://infra.bittokazi.com/gitlab-deploy/spring-boot-oauth2-multi-tenant-auth-server
          method: "POST"
          username: "n/a"
          password: "n/a"
          customHeaders: '{"Content-Type": "application/json", "X-Gitlab-Token": "eeeea9a0-9b4a-46fe-a7e4-c5ecff43b8f2"}'
          data: '{"ref": "refs/heads/main"}'
