name: Release
run-name: Release Version @${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release branch/tag version (eg. refs/tags/*, refs/head/main)"
        required: true
        default: "refs/tags"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repositoty
        uses: actions/checkout@v3
        with:
          repository: bittokazi/spring-boot-oauth2-multi-tenant-auth-server
          ref: ${{ github.event.inputs.version }}
          token: ${{ secrets.REPO_PAT }}

      - name: Log into registry registry.gitlab.com
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: bittokazi
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

      - name: Build and Push Java Backend Image
        run: docker build  --build-arg DEPLOY_ENV=prod . --file ./Dockerfile --tag registry.gitlab.com/bittokazi/spring-boot-oauth2-multi-tenant-auth-server/backend:latest && docker push registry.gitlab.com/bittokazi/spring-boot-oauth2-multi-tenant-auth-server/backend:latest
